client:
  globalTimeout: 8000
  maxThreadNumber: 10
  resiliency:
    maxRetries: 3
  app-homevision-staging:
    baseUrl: http://app-homevision-staging.herokuapp.com/api_project/
    pageCount: 10
    size: 10